package sipflow
import("errors";"fmt";"strconv";"strings";"time";"github.com/haarardin/sipflow/sdp")
var(ErrInvalidMessage=errors.New("sipflow: invalid SIP message");ErrMissingCallID=errors.New("sipflow: missing Call-ID"))
type ParseOptions struct{CaptureRaw bool}
func Parse(raw []byte,d Direction,m Meta,o ParseOptions)(Event,error){text:=strings.ReplaceAll(string(raw),"\r\n","\n");hp,body,_:=strings.Cut(text,"\n\n");ls:=strings.Split(hp,"\n");if len(ls)==0||strings.TrimSpace(ls[0])==""{return Event{},ErrInvalidMessage};e:=Event{ObservedAt:m.ObservedAt,Direction:d,CorrelationID:m.CorrelationID,LegID:m.LegID,LocalAddr:m.LocalAddr,RemoteAddr:m.RemoteAddr,Transport:m.Transport,Node:m.Node};if e.ObservedAt.IsZero(){e.ObservedAt=time.Now().UTC()};start:=strings.TrimSpace(ls[0]);if strings.HasPrefix(strings.ToUpper(start),"SIP/2.0 "){e.Kind=ResponseKind;p:=strings.SplitN(start," ",3);if len(p)<2{return Event{},ErrInvalidMessage};code,err:=strconv.Atoi(p[1]);if err!=nil{return Event{},fmt.Errorf("%w: status",ErrInvalidMessage)};e.StatusCode=code;if len(p)==3{e.Reason=strings.TrimSpace(p[2])}}else{e.Kind=RequestKind;p:=strings.Fields(start);if len(p)<3||!strings.EqualFold(p[len(p)-1],"SIP/2.0"){return Event{},ErrInvalidMessage};e.Method=strings.ToUpper(p[0]);e.RequestURI=p[1]};h:=headers(ls[1:]);e.CallID=hv(h,"call-id","i");if e.CallID==""{return Event{},ErrMissingCallID};e.From=hv(h,"from","f");e.To=hv(h,"to","t");e.FromURI=uri(e.From);e.ToURI=uri(e.To);e.FromTag=param(e.From,"tag");e.ToTag=param(e.To,"tag");e.TopVia=hv(h,"via","v");if i:=strings.IndexByte(e.TopVia,',');i>=0{e.TopVia=strings.TrimSpace(e.TopVia[:i])};e.TopViaBranch=param(e.TopVia,"branch");e.Contact=hv(h,"contact","m");e.ContentType=strings.TrimSpace(strings.Split(hv(h,"content-type","c"),";")[0]);if c:=hv(h,"cseq");c!=""{p:=strings.Fields(c);if len(p)>0{n,_:=strconv.ParseUint(p[0],10,32);e.CSeq=uint32(n)};if len(p)>1{e.CSeqMethod=strings.ToUpper(p[1])}};if e.Kind==RequestKind&&e.CSeqMethod==""{e.CSeqMethod=e.Method};if strings.EqualFold(e.ContentType,"application/sdp")&&strings.TrimSpace(body)!=""{x:=sdp.Parse(body);e.SDP=&SDPSummary{ConnectionAddress:x.ConnectionAddress,BundleMIDs:x.BundleMIDs,ICEUfrag:x.ICEUfrag,Fingerprint:x.Fingerprint};for _,mm:=range x.Media{sm:=SDPMedia{Type:mm.Type,Port:mm.Port,Protocol:mm.Protocol,Formats:mm.Formats,MID:mm.MID,Direction:mm.Direction,RTCPMux:mm.RTCPMux,Connection:mm.Connection};for _,c:=range mm.Codecs{sm.Codecs=append(sm.Codecs,SDPCodec{PayloadType:c.PayloadType,Name:c.Name,ClockRate:c.ClockRate,Channels:c.Channels})};e.SDP.Media=append(e.SDP.Media,sm)}};if o.CaptureRaw{e.Raw=string(raw)};return e,nil}
func headers(ls []string)map[string][]string{u:=[]string{};for _,l:=range ls{if len(l)>0&&(l[0]==' '||l[0]=='\t')&&len(u)>0{u[len(u)-1]+=" "+strings.TrimSpace(l)}else{u=append(u,l)}};h:=map[string][]string{};for _,l:=range u{n,v,ok:=strings.Cut(l,":");if ok{k:=strings.ToLower(strings.TrimSpace(n));h[k]=append(h[k],strings.TrimSpace(v))}};return h}
func hv(h map[string][]string,n ...string)string{for _,k:=range n{if v:=h[strings.ToLower(k)];len(v)>0{return v[0]}};return ""}
func uri(v string)string{v=strings.TrimSpace(v);if a:=strings.IndexByte(v,'<');a>=0{if b:=strings.IndexByte(v[a+1:],'>');b>=0{return strings.TrimSpace(v[a+1:a+1+b])}};if i:=strings.IndexByte(v,';');i>=0{v=v[:i]};p:=strings.Fields(v);if len(p)==0{return ""};return p[len(p)-1]}
func param(v,w string)string{p:=strings.Split(v,";");for _,x:=range p[1:]{k,val,ok:=strings.Cut(strings.TrimSpace(x),"=");if ok&&strings.EqualFold(k,w){return strings.Trim(strings.TrimSpace(val),"\"")}};return ""}
