package sipflow

import "time"

type Direction string
const ( Inbound Direction="inbound"; Outbound Direction="outbound" )
type Transport string
const ( TransportUDP Transport="UDP"; TransportTCP Transport="TCP"; TransportTLS Transport="TLS"; TransportWS Transport="WS"; TransportWSS Transport="WSS" )
type Meta struct { ObservedAt time.Time `json:"observed_at,omitempty"`; LocalAddr string `json:"local_addr,omitempty"`; RemoteAddr string `json:"remote_addr,omitempty"`; Transport Transport `json:"transport,omitempty"`; Node string `json:"node,omitempty"`; CorrelationID string `json:"correlation_id,omitempty"`; LegID string `json:"leg_id,omitempty"` }
type MessageKind string
const ( RequestKind MessageKind="request"; ResponseKind MessageKind="response" )
type Event struct { Sequence uint64 `json:"sequence"`; ObservedAt time.Time `json:"observed_at"`; Direction Direction `json:"direction"`; Kind MessageKind `json:"kind"`; Method string `json:"method,omitempty"`; RequestURI string `json:"request_uri,omitempty"`; StatusCode int `json:"status_code,omitempty"`; Reason string `json:"reason,omitempty"`; CallID string `json:"call_id"`; CorrelationID string `json:"correlation_id,omitempty"`; LegID string `json:"leg_id,omitempty"`; CSeq uint32 `json:"cseq,omitempty"`; CSeqMethod string `json:"cseq_method,omitempty"`; From string `json:"from,omitempty"`; FromURI string `json:"from_uri,omitempty"`; FromTag string `json:"from_tag,omitempty"`; To string `json:"to,omitempty"`; ToURI string `json:"to_uri,omitempty"`; ToTag string `json:"to_tag,omitempty"`; TopVia string `json:"top_via,omitempty"`; TopViaBranch string `json:"top_via_branch,omitempty"`; Contact string `json:"contact,omitempty"`; ContentType string `json:"content_type,omitempty"`; LocalAddr string `json:"local_addr,omitempty"`; RemoteAddr string `json:"remote_addr,omitempty"`; Transport Transport `json:"transport,omitempty"`; Node string `json:"node,omitempty"`; Retransmission bool `json:"retransmission,omitempty"`; SDP *SDPSummary `json:"sdp,omitempty"`; Raw string `json:"raw,omitempty"` }
type Transaction struct { Key string `json:"key"`; CallID string `json:"call_id"`; Branch string `json:"branch,omitempty"`; Method string `json:"method"`; CSeq uint32 `json:"cseq,omitempty"`; FirstSeenAt time.Time `json:"first_seen_at"`; LastSeenAt time.Time `json:"last_seen_at"`; EventSequences []uint64 `json:"event_sequences"`; Retransmissions int `json:"retransmissions"`; FinalStatus int `json:"final_status,omitempty"` }
type Dialog struct { Key string `json:"key"`; CallID string `json:"call_id"`; TagA string `json:"tag_a"`; TagB string `json:"tag_b"`; FirstSeenAt time.Time `json:"first_seen_at"`; LastSeenAt time.Time `json:"last_seen_at"`; EventSequences []uint64 `json:"event_sequences"` }
type FlowState string
const ( StateUnknown FlowState="unknown"; StateInviting FlowState="inviting"; StateRinging FlowState="ringing"; StateEarlyMedia FlowState="early_media"; StateEstablished FlowState="established"; StateTerminating FlowState="terminating"; StateEnded FlowState="ended"; StateFailed FlowState="failed"; StateCancelled FlowState="cancelled" )
type Metrics struct { FirstProvisionalMS int64 `json:"first_provisional_ms,omitempty"`; RingingMS int64 `json:"ringing_ms,omitempty"`; SetupMS int64 `json:"setup_ms,omitempty"`; TalkMS int64 `json:"talk_ms,omitempty"` }
type Flow struct { ID string `json:"id"`; CallIDs []string `json:"call_ids"`; State FlowState `json:"state"`; StartedAt time.Time `json:"started_at,omitempty"`; FirstSeenAt time.Time `json:"first_seen_at"`; LastSeenAt time.Time `json:"last_seen_at"`; AnsweredAt *time.Time `json:"answered_at,omitempty"`; EndedAt *time.Time `json:"ended_at,omitempty"`; FinalStatus int `json:"final_status,omitempty"`; FinalReason string `json:"final_reason,omitempty"`; Cancelled bool `json:"cancelled,omitempty"`; EarlyMedia bool `json:"early_media,omitempty"`; Events []Event `json:"events"`; Transactions map[string]*Transaction `json:"transactions"`; Dialogs map[string]*Dialog `json:"dialogs"`; Metrics Metrics `json:"metrics"`; Retransmissions int `json:"retransmissions"`; firstProvisionalAt *time.Time; ringingAt *time.Time }
type SDPSummary struct { ConnectionAddress string `json:"connection_address,omitempty"`; BundleMIDs []string `json:"bundle_mids,omitempty"`; ICEUfrag string `json:"ice_ufrag,omitempty"`; Fingerprint string `json:"fingerprint,omitempty"`; Media []SDPMedia `json:"media,omitempty"` }
type SDPMedia struct { Type string `json:"type"`; Port int `json:"port"`; Protocol string `json:"protocol"`; Formats []string `json:"formats,omitempty"`; Codecs []SDPCodec `json:"codecs,omitempty"`; MID string `json:"mid,omitempty"`; Direction string `json:"direction,omitempty"`; RTCPMux bool `json:"rtcp_mux,omitempty"`; Connection string `json:"connection,omitempty"` }
type SDPCodec struct { PayloadType int `json:"payload_type"`; Name string `json:"name"`; ClockRate int `json:"clock_rate,omitempty"`; Channels int `json:"channels,omitempty"` }
